name: Bonjour
on:
  - push
jobs:
  
  run_maven:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Check Version
        run: java -version && mvn -version && mvn help:effective-pom